### ISSUE TITLE
It seems that fifteen_api.py is outdated

### ISSUE THREAD

**Issue by MC41Games** [wafflecomposite/15.ai-Python-API#1]
Hello, recently I have tried to run the file fifteen_api.py locally, and I got this error:
> ValueError: [15API]Error: can't find characters data in app js. Most likely, the format has changed and requires updating the code.

So I thought that the code was made for working with previous versions of the app.XXXXXXXX.js file, then I went to https://web.archive.org/ and got some of the old versions of the app.XXXXXXXX.js file, and then I forced fifteen_api.py to use them, that fixed the previous error, but it gave me a new error:
> ValueError: [15API]Error while parsing app js. Most likely, the format has changed and requires updating the code.

**Comment by Morplson** [comment]
I get the same error^^

**Comment by wafflecomposite** [comment]
Thank you for noticing, I'm on it.
I will also make parsing the list of characters optional, as it's... actually should be optional.

**Comment by wafflecomposite** [comment]
On the other hand, handling the JS file was a big mistake. I removed that part of the code.
This will not affect the main functionality, just from now on the script will not show the list of characters and will not validate the name and emotion of the character before sending the request.

Names and emotions of the characters can be obtained at https://fifteen.ai/app as always. 

https://github.com/wafflecomposite/15.ai-Python-API/commit/76df4a9d56dd3a3c5314d8b192c3031d7e467f19

Please check that it works now, thanks
