### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by ghost** [wafflecomposite/15.ai-Python-API#4]
Hey wafflecomposite,

Where can I contact you to try and make a js verison of this, or to help me at least, if you can't thats ok, I am just confused on how you write the data to the file, do you know js and can you explain how you did it in python?

**Comment by wafflecomposite** [comment]
Hi. I don't know the js very well, and I'm not sure I can help, but overall it seems to be quite an straightforward task.
Response to https://api.15.ai/app/getAudioFile request is exactly those bytes I'm writing to the file, using python built-in methods.
So you are looking for the direct way to save the response(byte array) to file as is.

**Comment by ghost** [comment]
Yeah I figured it out, thanks!
