### ISSUE TITLE
Returning 404

### ISSUE THREAD

**Issue by exdarku** [wafflecomposite/15.ai-Python-API#5]
I tried with the example in the readme, and it returns 404. I tried finding any API guide about 15.ai, but google doesn't give me anything for some reason.

**Comment by DigiDuncan** [comment]
Having the same issue. Changing the header's `user-agent` value to `Mozilla/5.0` returns a 502 instead. Any ideas for a work-around?

**Comment by yolocat-dev** [comment]
Same here... no clue what do do now

**Comment by dray-cyber** [comment]
All of you lads I have fixed the issue check out my new 15.Ai Apiv2 repo

**Comment by dray-cyber** [comment]
I found the new api link although I can not get this to work

**Comment by dray-cyber** [comment]
tts_url = "https://api.15.ai/app/getAudioFile5" to clarify I can not get it to work in python, I do get results from node js though.

**Comment by DigiDuncan** [comment]
Got a hack working in my own program by making a function e.g.:

```python
import requests

url = "https://api.15.ai/app/getAudioFile5"
headers = {'authority': 'api.15.ai',
           'access-control-allow-origin': '*',
           'accept': 'application/json, text/plain, */*',
           'dnt': '1',
           'user-agent': 'Mozilla/5.0,
           'content-type': 'application/json;charset=UTF-8',
           'sec-gpc': '1',
           'origin': 'https://15.ai',
           'sec-fetch-site': 'same-site',
           'sec-fetch-mode': 'cors',
           'sec-fetch-dest': 'empty',
           'referer': 'https://15.ai/',
           'accept-language': 'en-US,en;q=0.9'}

def get_sound(character: str, emotion: str, text: str):
    response = requests.post(url, json = {
        "character": character,
        "emotion": emotion,
        "text": text
    }, headers = headers)

    if response.status_code != 200:
        raise RuntimeError(f"15.ai responded with code {response.status_code}.")

    data_json = response.json()
    wav_name = data_json["wavNames"][0]

    second_response = requests.get(cdn_url + wav_name)

    if second_response.status_code != 200:
        raise RuntimeError(f"15.ai CDN responded with code {second_response.status_code}.")

    print("Audio success!")

    return second_response.content
```

**Comment by sbeer3** [comment]
> Got a hack working in my own program by making a function e.g.:
> 
> ```python
> import requests
> 
> url = "https://api.15.ai/app/getAudioFile5"
> headers = {'authority': 'api.15.ai',
>            'access-control-allow-origin': '*',
>            'accept': 'application/json, text/plain, */*',
>            'dnt': '1',
>            'user-agent': 'Mozilla/5.0,
>            'content-type': 'application/json;charset=UTF-8',
>            'sec-gpc': '1',
>            'origin': 'https://15.ai',
>            'sec-fetch-site': 'same-site',
>            'sec-fetch-mode': 'cors',
>            'sec-fetch-dest': 'empty',
>            'referer': 'https://15.ai/',
>            'accept-language': 'en-US,en;q=0.9'}
> 
> def get_sound(character: str, emotion: str, text: str):
>     response = requests.post(url, json = {
>         "character": character,
>         "emotion": emotion,
>         "text": text
>     }, headers = headers)
> 
>     if response.status_code != 200:
>         raise RuntimeError(f"15.ai responded with code {response.status_code}.")
> 
>     data_json = response.json()
>     wav_name = data_json["wavNames"][0]
> 
>     second_response = requests.get(cdn_url + wav_name)
> 
>     if second_response.status_code != 200:
>         raise RuntimeError(f"15.ai CDN responded with code {second_response.status_code}.")
> 
>     print("Audio success!")
> 
>     return second_response.content
> ```

cdn_url is undefinded?

**Comment by DigiDuncan** [comment]
> cdn_url is undefinded?

Apologies! 

`cdn_url = "https://cdn.15.ai/audio/"`

**Comment by wafflecomposite** [comment]
Hi!
Thanks to everyone who posted!

I have updated the files to reflect the new changes on 15.ai, it should work now.
Note that emotions are now contextual (or you should set them in text using separators, see https://15.ai/guide), so "emotion" argument is gone, this will break compatibility with previous version. Just remove emotion arguments from your script calls.

Everything else should work as before.
For now, I'm closing this issue, but let me know if there is any problems still.

https://github.com/wafflecomposite/15.ai-Python-API/commit/a43c43c95a12cbb9bbb215a486bb4c9d28f7e6cf
