### ISSUE TITLE
problems installing python3

### ISSUE THREAD

**Issue by TismoDito** [wafflecomposite/15.ai-Python-API#6]
How can I install Python3 in Google Colab without facing these 2 errors?
1. ERROR: Could not find a version that satisfies the requirement fifteen_api (from versions: none)
2. ERROR: No matching distribution found for fifteen_api

**Comment by wafflecomposite** [comment]
Apologies for not noticing your issue earlier.

This api wrapper is not distributed as a installable python package. To use it, you have to download [fifteen_api.py](https://github.com/wafflecomposite/15.ai-Python-API/blob/master/fifteen_api.py) or copy in any way you like locally.

Then in the same folder where you copied it, create your `.py` file. There you will be able to import it by
`from fifteen_api import FifteenAPI`

Sorry for the inconvenience.

**Comment by wafflecomposite** [comment]
If for some reason it causes problems in the Google Colab specifically - I can't tell you how to solve it, since I haven't worked with it, however there absolutely should be an option to import classes from a local file since it's a pretty basic thing to do
