### ISSUE TITLE
Glados voice not working

### ISSUE THREAD

**Issue by Wilbatronic** [wafflecomposite/15.ai-Python-API#7]
The glados voice does not work as when I type it in eg. `response = tts_api.save_to_file("GlaDOS", text)` it just gives me the 442 error.

**Comment by wafflecomposite** [comment]
API is case-sensitive, so you have to enter the name of the character exactly as it is listed on the 15.ai
`442` usually means that a character with this name wasn't found.

I just tried `response = tts_api.save_to_file("GLaDOS", "This is a test")` and it worked. 
Note the capital letter "L" in "GLaDOS". In the example you gave, this letter is lowercase, which caused the problem.
